# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  shoponlineapi:
    image: shoponlineapi
    build:
      context: .
      dockerfile: ShopOnline.WebAPI/Dockerfile
    ports:
      - 7142:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7142;http://+:7142;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=lol
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro  
      
