version: '3.4'

services:
  shoponlineweb:
    image: shoponlineweb
    build:
      context: .
      dockerfile: ShopOnline.Web/Dockerfile
    ports:
      - "5232:80"
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"
      - ASPNETCORE_URLS="https://+:443;http://+:80"
      - ASPNETCORE_Kestrel__Certificates__Default__Password="lol"
      - ASPNETCORE_Kestrel__Certificates__Default__Path="/https/localhost.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
      

  shoponlineapi:
    image: shoponlineapi
    build:
      context: .
      dockerfile: "ShopOnline.WebAPI/Dockerfile"
    depends_on:
      - "database"
    ports:
      - "7142:443"
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"
      - ASPNETCORE_URLS="https://+:443;http://+:80"
      - ASPNETCORE_Kestrel__Certificates__Default__Password="lol"
      - ASPNETCORE_Kestrel__Certificates__Default__Path="/https/localhost.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro

  database:
    container_name: postgres
    image: "postgres"
    restart: always
    ports:
       - 5432:5432
    environment:
      POSTGRES_PASSWORD: lol


    






# # Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

# version: '3.4'

# services:
#   shoponlineweb:
#     image: shoponlineweb
#     build:
#       context: .
#       dockerfile: ShopOnline.Web/Dockerfile
#     ports:
#       - 5232:80
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_URLS=https://+:5232;http://+:5232;
#       - ASPNETCORE_Kestrel__Certificates__Default__Password=lol
#       - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

#     volumes:
#       - ~/.aspnet/https:/https:ro  


#   shoponlineapi:
#     image: shoponlineapi
#     build:
#       context: .
#       dockerfile: ShopOnline.WebAPI/Dockerfile
#     ports:
#       - 7142:443
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_URLS=https://+:7142;http://+:7142;
#       - ASPNETCORE_Kestrel__Certificates__Default__Password=lol
#       - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

#     volumes:
#       - ~/.aspnet/https:/https:ro  


  

    


